version: '3.9'
services:
  nats:
    image: docker.io/nats:2.9.20
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats:/data
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
  postgres:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - PGDEBUG=true
      - POSTGRES_USER=diana
      - POSTGRES_DB=wb
      - PGSSLMODE=disable
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6532:5432"
  memcached:
    image: sameersbn/memcached:1.5.6-2
    ports:
      - "11211:11211"
    restart: always

volumes:
  nats:
  db-data:
